schemaVersion: 2.1.0
metadata:
  name: go-helloworld
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: go-cli
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-0e189d9
      endpoints:
        - name: webapp
          targetPort: 8080
      memoryLimit: 4Gi
      memoryRequest: 256Mi
      cpuLimit: 200m
      cpuRequest: 30m
  - name: projects
    volume: {ephemeral: true}
commands:
  - id: run
    exec:
      component: go-cli
      commandLine: "go run main.go"
      workingDir: $PROJECT_SOURCE
  - id: stop
    exec:
      component: go-cli
      commandLine: "kill $(pidof go)"
      workingDir: $PROJECT_SOURCE

