schemaVersion: 2.1.0
metadata:
  name: sfdx-helloworld
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: sfdx
    container:
      image: salesforce/salesforcedx
      memoryLimit: 4Gi
      memoryRequest: 256Mi
  - name: projects
    volume: {ephemeral: true}
commands:
  - id: create
    exec:
      component: sfdx
      commandLine: "sfdx force:project:create -n sampleproj"
      workingDir: $PROJECT_SOURCE
  - id: pull
    exec:
      component: sfdx
      commandLine: "sfdx force:source:pull"
      workingDir: $PROJECT_SOURCE
  - id: push
    exec:
      component: sfdx
      commandLine: "sfdx force:source:push"
      workingDir: $PROJECT_SOURCE
