schemaVersion: 2.1.0
metadata:
  name: go-helloworld
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: go-cli
    container:
      image: salesforce/salesforcedx
      endpoints:
        - name: webapp
          targetPort: 8080
      memoryLimit: 4Gi
      memoryRequest: 256Mi
  - name: projects
    volume: {ephemeral: true}
commands:
  - id: run
    exec:
      component: go-cli
      commandLine: "go run main.go"
      workingDir: $PROJECT_SOURCE
  - id: stop
    exec:
      component: go-cli
      commandLine: "kill $(pidof go)"
      workingDir: $PROJECT_SOURCE
  - id: build
    exec:
      component: go-cli
      commandLine: "go main.go"
      workingDir: $PROJECT_SOURCE
