schemaVersion: 2.1.0
metadata:
  name: sfdx-helloworld
  language: sfdx
components:
  - container:
      endpoints:
        - name: http
          targetPort: 8080
      image: salesforce/salesforcedx
      memoryLimit: 1024Mi
      mountSources: true
    name: runtime